export default {
  src: '',
  iosSrc: '',
  poster: '',
  alt: '',
  loading: 'auto',
  reveal: 'auto',
  modelCacheSize: 5,
  powerPreference: 'high-performance',
  ar: false,
  arModes: 'webxr scene-viewer quick-look',
  arScale: 'auto',
  arPlacement: 'floor',
  autoPlay: false,
  autoRotate: false,
  autoRotateDelay: 3000,
  interactionPromptStyle: 'wiggle',
  interactionPromptThresold: 3000,
  cameraControls: false,
  cameraOrbit: '',
  cameraTarget: '',
  exposure: 1,
  shadowIntensity: 0,
  shadowSoftness: 1,
  arButtonText: 'View'
}
